/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.cl.slack.audio_foreign.opensl_example;

public class opensl_example {
    public static void start_process() {
        opensl_exampleJNI.start_process();
    }

    public static void stop_process() {
        opensl_exampleJNI.stop_process();
    }

}
